#!/usr/bin/env bash
# Agent Wiki — single-command Docker Compose installer.
#
#   curl -fsSL https://raw.githubusercontent.com/onyx-dot-app/agent-wiki/main/install.sh | bash
#
# Brings up Postgres + backend + workers + frontend + nginx on this host.
# Auth is the built-in email/password flow; the first account you sign up
# becomes the admin.

set -euo pipefail

REPO_URL="${AGENT_WIKI_REPO:-https://github.com/onyx-dot-app/agent-wiki.git}"
REF="${AGENT_WIKI_REF:-main}"
DIR="${AGENT_WIKI_DIR:-$PWD/agent-wiki}"
PORT="${AGENT_WIKI_PORT:-8090}"

say()  { printf "\033[1;36m==>\033[0m %s\n" "$*"; }
warn() { printf "\033[1;33m!!\033[0m  %s\n" "$*" >&2; }
die()  { printf "\033[1;31mxx\033[0m  %s\n" "$*" >&2; exit 1; }

# ---- prerequisites ---------------------------------------------------------
command -v git >/dev/null    || die "git is required"
command -v docker >/dev/null || die "docker is required — install from https://docs.docker.com/get-docker/"
docker info >/dev/null 2>&1  || die "docker daemon is not running"
if   docker compose version >/dev/null 2>&1; then COMPOSE=(docker compose)
elif command -v docker-compose >/dev/null;    then COMPOSE=(docker-compose)
else die "docker compose (v2) or docker-compose is required"
fi
command -v openssl >/dev/null || die "openssl is required (for SECRET_KEY)"

# ---- fetch source ----------------------------------------------------------
if [ -d "$DIR/.git" ]; then
  say "Updating existing checkout at $DIR"
  git -C "$DIR" fetch --depth=1 origin "$REF"
  git -C "$DIR" checkout -q "$REF"
  git -C "$DIR" reset --hard -q "origin/$REF"
else
  say "Cloning $REPO_URL (ref: $REF) into $DIR"
  git clone --depth=1 --branch "$REF" "$REPO_URL" "$DIR"
fi
cd "$DIR"

# ---- .env ------------------------------------------------------------------
if [ ! -f .env ]; then
  say "Generating .env with a fresh SECRET_KEY"
  SECRET_KEY="$(openssl rand -hex 32)"
  cat > .env <<EOF
# Agent Wiki — generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
SECRET_KEY=$SECRET_KEY
# LLM provider keys are configured in-app under Admin → LLM after first login.
EOF
else
  say "Reusing existing .env"
fi

# ---- bring it up -----------------------------------------------------------
say "Building images (first run takes a few minutes)"
"${COMPOSE[@]}" build

say "Starting containers"
"${COMPOSE[@]}" up -d

# ---- wait for the app ------------------------------------------------------
say "Waiting for the app to come up on http://localhost:$PORT"
UP=0
for _ in $(seq 1 60); do
  if curl -fsS "http://localhost:$PORT" >/dev/null 2>&1; then
    UP=1
    break
  fi
  sleep 2
done

if [ "$UP" -ne 1 ]; then
  warn "App didn't respond within 2 minutes. Check logs with:"
  warn "  cd $DIR && ${COMPOSE[*]} logs -f"
  exit 1
fi

say "Agent Wiki is up: http://localhost:$PORT"
say "Create the first account at http://localhost:$PORT — it becomes admin."
say "Then go to Admin → LLM to configure a model provider."

# ---- star prompt -----------------------------------------------------------
# Piped from curl, stdin isn't a TTY — read directly from the terminal.
prompt_star() {
  [ -r /dev/tty ] || return 0
  printf "\n\033[1;36m==>\033[0m Enjoying Agent Wiki? Star the repo on GitHub? [Y/n] "
  local reply=""
  read -r reply </dev/tty || return 0
  case "${reply:-y}" in
    n|N|no|No|NO) return 0 ;;
  esac

  if ! command -v gh >/dev/null 2>&1; then
    printf "    (skipped — GitHub CLI not installed; star us at https://github.com/onyx-dot-app/agent-wiki ★)\n"
    return 0
  fi
  if ! gh auth status >/dev/null 2>&1; then
    printf "    (skipped — gh isn't signed in; run \`gh auth login\` then \`gh api -X PUT user/starred/onyx-dot-app/agent-wiki\`)\n"
    return 0
  fi
  if gh api -X PUT user/starred/onyx-dot-app/agent-wiki >/dev/null 2>&1; then
    printf "    Thanks! ⭐\n"
  fi
  return 0
}

prompt_star
exit 0
