"""SQLAlchemy ORM models — the source of truth for the app's schema.

``init_db()`` in ``app.db.session`` runs ``alembic upgrade head``;
schema changes flow through autogenerated migration files in
``app/db/migrations/versions/``. So when you edit a model here, also
run ``cd backend && alembic revision --autogenerate -m "<slug>"`` and
review the emitted diff before committing. The bootstrap migration
``0001_initial`` materializes the entire current schema via
``Base.metadata.create_all`` — every migration after it is an explicit
``op.alter_table`` / ``op.add_column`` diff. Postgres-specific bits
that ORM declarations can't express (extension creation, pgmq queue
creation) also live in ``0001_initial``.

Keep these models *narrow* — they describe DB shape. HTTP request /
response shapes belong in ``app/models/`` (pydantic). Repos return
dicts derived from these objects so callers don't depend on the ORM.
"""
from __future__ import annotations

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    ForeignKey,
    Index,
    Integer,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Default for TEXT timestamp columns. Stored as ISO-formatted strings so
# Python-side ISO comparisons (e.g. ``expires_at > _iso(_now())``) work
# without per-call casts. Switching these to ``TIMESTAMPTZ`` would mean
# updating every site that passes / serializes the value — not worth it
# for the marginal type safety.
_NOW_TEXT_DEFAULT = text("to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')")


class Base(DeclarativeBase):
    pass


# --------------------------------------------------------------------------- #
# Users + auth                                                                #
# --------------------------------------------------------------------------- #


class User(Base):
    __tablename__ = "users"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    email: Mapped[str] = mapped_column(Text, unique=True, nullable=False)
    name: Mapped[str | None] = mapped_column(Text)
    # Null when AUTH_MODE=oidc.
    password_hash: Mapped[str | None] = mapped_column(Text)
    is_admin: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("FALSE"))
    created_at: Mapped[str] = mapped_column(Text, nullable=False, server_default=_NOW_TEXT_DEFAULT)


class McpConnection(Base):
    __tablename__ = "mcp_connections"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    user_id: Mapped[str] = mapped_column(
        Text, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    name: Mapped[str] = mapped_column(Text, nullable=False)
    transport: Mapped[str] = mapped_column(Text, nullable=False)   # "stdio" | "http"
    config_json: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[str] = mapped_column(Text, nullable=False, server_default=_NOW_TEXT_DEFAULT)


# --------------------------------------------------------------------------- #
# Documents (metadata) — canonical content lives in git                       #
# --------------------------------------------------------------------------- #


class Document(Base):
    __tablename__ = "documents"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    path: Mapped[str] = mapped_column(Text, unique=True, nullable=False)
    title: Mapped[str | None] = mapped_column(Text)
    updated_at: Mapped[str] = mapped_column(Text, nullable=False, server_default=_NOW_TEXT_DEFAULT)


# --------------------------------------------------------------------------- #
# Triggers — git-backed YAML is the source of truth; this is a lookup cache   #
# --------------------------------------------------------------------------- #


class Trigger(Base):
    __tablename__ = "triggers"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    owner_user_id: Mapped[str] = mapped_column(
        Text, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    scope_path: Mapped[str] = mapped_column(Text, nullable=False)
    kind: Mapped[str] = mapped_column(Text, nullable=False)        # "delta" | "schedule"
    nl_description: Mapped[str] = mapped_column(Text, nullable=False)
    action_json: Mapped[str] = mapped_column(Text, nullable=False)
    schedule_cron: Mapped[str | None] = mapped_column(Text)
    enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("TRUE"))
    file_path: Mapped[str | None] = mapped_column(Text)
    last_edited_at: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[str] = mapped_column(Text, nullable=False, server_default=_NOW_TEXT_DEFAULT)


# --------------------------------------------------------------------------- #
# Audit log                                                                   #
# --------------------------------------------------------------------------- #


class Event(Base):
    __tablename__ = "events"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    ts: Mapped[str] = mapped_column(Text, nullable=False, server_default=_NOW_TEXT_DEFAULT)
    kind: Mapped[str] = mapped_column(Text, nullable=False)
    actor: Mapped[str | None] = mapped_column(Text)
    target: Mapped[str | None] = mapped_column(Text)
    payload_json: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'{}'"))

    __table_args__ = (
        Index("idx_events_ts", "ts"),
        Index("idx_events_kind_ts", "kind", "ts"),
    )


# --------------------------------------------------------------------------- #
# BM25 search index (pg_textsearch)                                           #
# --------------------------------------------------------------------------- #


class DocumentFts(Base):
    """Wiki search index — title + body indexed via pg_textsearch.

    The BM25 access method (``USING bm25``) is registered by the
    extension; the ``0001_initial`` migration runs
    ``CREATE EXTENSION pg_textsearch`` before ``Base.metadata.create_all``
    so the index DDL succeeds.
    """

    __tablename__ = "documents_fts"

    doc_id: Mapped[str] = mapped_column(Text, primary_key=True)
    path: Mapped[str] = mapped_column(Text, nullable=False)
    title: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("''"))
    body: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("''"))

    __table_args__ = (
        Index(
            "documents_fts_bm25",
            text("(coalesce(title, '') || ' ' || coalesce(body, ''))"),
            postgresql_using="bm25",
            # Quote the value explicitly — SQLAlchemy's WITH renderer passes
            # the dict value through as-is, and pg_textsearch's examples all
            # use the quoted form (``text_config = 'english'``).
            postgresql_with={"text_config": "'english'"},
        ),
    )


# --------------------------------------------------------------------------- #
# Single-row settings tables — id=1 always                                    #
# --------------------------------------------------------------------------- #


class LLMSettings(Base):
    __tablename__ = "llm_settings"

    # ``id`` is always 1 — the CHECK below + the singleton constraint enforce
    # that. Mark autoincrement=False so SQLAlchemy doesn't synthesize a
    # SERIAL sequence we'd never read from.
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=False)
    provider: Mapped[str] = mapped_column(Text, nullable=False)
    model: Mapped[str] = mapped_column(Text, nullable=False)
    anthropic_api_key: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("''"))
    openai_api_key: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("''"))
    gemini_api_key: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("''"))
    ollama_base_url: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("''"))
    updated_at: Mapped[str] = mapped_column(Text, nullable=False, server_default=_NOW_TEXT_DEFAULT)

    __table_args__ = (CheckConstraint("id = 1", name="llm_settings_singleton"),)


class WebSettings(Base):
    __tablename__ = "web_settings"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=False)
    serper_api_key: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("''"))
    firecrawl_api_key: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("''"))
    updated_at: Mapped[str] = mapped_column(Text, nullable=False, server_default=_NOW_TEXT_DEFAULT)

    __table_args__ = (CheckConstraint("id = 1", name="web_settings_singleton"),)


class IngestSettings(Base):
    __tablename__ = "ingest_settings"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=False)
    max_doc_chars: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("100000")
    )
    updated_at: Mapped[str] = mapped_column(Text, nullable=False, server_default=_NOW_TEXT_DEFAULT)

    __table_args__ = (CheckConstraint("id = 1", name="ingest_settings_singleton"),)


# --------------------------------------------------------------------------- #
# Agent activity registry                                                     #
# --------------------------------------------------------------------------- #


class AgentActivity(Base):
    __tablename__ = "agent_activity"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    user_id: Mapped[str] = mapped_column(
        Text, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    # Null when the agent didn't name itself.
    agent_name: Mapped[str | None] = mapped_column(Text)
    doc_path: Mapped[str] = mapped_column(Text, nullable=False)
    activity: Mapped[str] = mapped_column(Text, nullable=False)
    description: Mapped[str | None] = mapped_column(Text)   # null = "N/A" in rendered frontmatter
    registered_at: Mapped[str] = mapped_column(
        Text, nullable=False, server_default=_NOW_TEXT_DEFAULT
    )
    expires_at: Mapped[str] = mapped_column(Text, nullable=False)   # ISO 8601 UTC

    __table_args__ = (
        CheckConstraint(
            "activity IN ('read', 'wrote')", name="agent_activity_kind_check"
        ),
        # Postgres 15+ NULLS NOT DISTINCT lets nullable agent_name participate
        # in uniqueness directly — no COALESCE-to-empty-string workaround.
        UniqueConstraint(
            "user_id", "agent_name", "doc_path", "activity",
            name="idx_agent_activity_natural_key",
            postgresql_nulls_not_distinct=True,
        ),
        Index("idx_agent_activity_doc_path", "doc_path"),
        Index("idx_agent_activity_expires_at", "expires_at"),
    )


# --------------------------------------------------------------------------- #
# Cron state — per-(queue, task) last-fired timestamp so the periodic         #
# scheduler can survive restarts without silently dropping or stampeding      #
# missed fires. See app/tasks/queue.py:_run_periodic_scheduler.               #
# --------------------------------------------------------------------------- #


class CronState(Base):
    __tablename__ = "cron_state"

    queue_name: Mapped[str] = mapped_column(Text, primary_key=True)
    task_name: Mapped[str] = mapped_column(Text, primary_key=True)
    last_fired_at: Mapped[str | None] = mapped_column(Text)
