"""SQLAlchemy ORM models — the source of truth for the app's schema.

``init_db()`` in ``app.db.session`` runs ``alembic upgrade head``;
schema changes flow through autogenerated migration files in
``app/db/migrations/versions/``. So when you edit a model here, also
run ``cd backend && alembic revision --autogenerate -m "<slug>"`` and
review the emitted diff before committing. The bootstrap migration
``0001_initial`` materializes the entire current schema via
``Base.metadata.create_all`` — every migration after it is an explicit
``op.alter_table`` / ``op.add_column`` diff.

Keep these models *narrow* — they describe DB shape. HTTP request /
response shapes belong in ``app/models/`` (pydantic). Repos return
dicts derived from these objects so callers don't depend on the ORM.
"""
from __future__ import annotations

from typing import Any

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    ForeignKey,
    Index,
    Integer,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Default for TEXT timestamp columns. Stored as ISO-formatted strings so
# Python-side ISO comparisons (e.g. ``expires_at > _iso(_now())``) work
# without per-call casts. Switching these to ``TIMESTAMPTZ`` would mean
# updating every site that passes / serializes the value — not worth it
# for the marginal type safety.
_NOW_TEXT_DEFAULT = text("to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')")


class Base(DeclarativeBase):
    pass


# --------------------------------------------------------------------------- #
# Users + auth                                                                #
# --------------------------------------------------------------------------- #


class User(Base):
    __tablename__ = "users"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    email: Mapped[str] = mapped_column(Text, unique=True, nullable=False)
    name: Mapped[str | None] = mapped_column(Text)
    # Null when AUTH_MODE=oidc.
    password_hash: Mapped[str | None] = mapped_column(Text)
    is_admin: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("FALSE"))
    created_at: Mapped[str] = mapped_column(Text, nullable=False, server_default=_NOW_TEXT_DEFAULT)
    # Per-user preferences (theme, timezone, etc.). Shape is enforced by the
    # ``UserSettings`` pydantic model in ``app/models/user_settings.py``;
    # the column itself is a free-form JSONB so adding a new preference
    # doesn't require a migration. Defaults to ``{}``; the API fills in
    # field defaults from the pydantic model on read.
    settings: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )


class McpConnection(Base):
    __tablename__ = "mcp_connections"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    user_id: Mapped[str] = mapped_column(
        Text, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    name: Mapped[str] = mapped_column(Text, nullable=False)
    transport: Mapped[str] = mapped_column(Text, nullable=False)   # "stdio" | "http"
    config_json: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[str] = mapped_column(Text, nullable=False, server_default=_NOW_TEXT_DEFAULT)


class McpToken(Base):
    """Personal API token an MCP client (Claude Code, Cursor, …) uses to
    authenticate against the inbound MCP server. Hashed-at-rest with
    bcrypt; raw value is shown to the user once at creation and never
    persisted.

    The token's user identity is what the server pretends is logged in
    for every request — see ``app/mcp_server/auth.py`` (when it lands)
    and the design at ``local_data/wiki/mcp-server/mcp-server.md``.
    """

    __tablename__ = "mcp_tokens"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    user_id: Mapped[str] = mapped_column(
        Text, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    name: Mapped[str] = mapped_column(Text, nullable=False)
    token_hash: Mapped[str] = mapped_column(Text, unique=True, nullable=False)
    created_at: Mapped[str] = mapped_column(Text, nullable=False, server_default=_NOW_TEXT_DEFAULT)
    last_used_at: Mapped[str | None] = mapped_column(Text)

    __table_args__ = (Index("idx_mcp_tokens_user", "user_id"),)


class McpJob(Base):
    """Async job row backing ``update_doc_nl`` over the inbound MCP
    server. Each call to the tool inserts one row; the worker
    (``app.tasks.wiki_update.agent_update_document_nl``) updates
    ``status`` / ``result_json`` / ``error`` / ``finished_at`` as it
    runs.

    Idempotency key (when provided or computed) lets a chatty agent
    retry the same instruction without enqueueing duplicate LLM
    passes — the second call returns the existing job. The unique
    index is partial so unkeyed jobs don't collide.

    See ``local_data/wiki/mcp-server/mcp-server.md`` (Phase 6).
    """

    __tablename__ = "mcp_jobs"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    user_id: Mapped[str] = mapped_column(
        Text, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    kind: Mapped[str] = mapped_column(Text, nullable=False)        # "update_doc_nl"
    status: Mapped[str] = mapped_column(Text, nullable=False)      # pending|running|succeeded|failed
    idempotency_key: Mapped[str | None] = mapped_column(Text)
    payload_json: Mapped[str] = mapped_column(Text, nullable=False)
    result_json: Mapped[str | None] = mapped_column(Text)
    error: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[str] = mapped_column(
        Text, nullable=False, server_default=_NOW_TEXT_DEFAULT
    )
    finished_at: Mapped[str | None] = mapped_column(Text)

    __table_args__ = (
        Index(
            "idx_mcp_jobs_idemp",
            "user_id", "idempotency_key",
            unique=True,
            postgresql_where=text("idempotency_key IS NOT NULL"),
        ),
        Index("idx_mcp_jobs_user", "user_id"),
        # Used by the debounce check: most-recent succeeded job for a
        # (user, path) pair within the last N seconds. Path lives in
        # payload_json so we can't index it cheaply; the user-scope
        # index is enough — the worker only walks rows within the
        # debounce window.
    )


# --------------------------------------------------------------------------- #
# Documents (metadata) — canonical content lives in git                       #
# --------------------------------------------------------------------------- #


class Document(Base):
    __tablename__ = "documents"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    path: Mapped[str] = mapped_column(Text, unique=True, nullable=False)
    title: Mapped[str | None] = mapped_column(Text)
    updated_at: Mapped[str] = mapped_column(Text, nullable=False, server_default=_NOW_TEXT_DEFAULT)


# --------------------------------------------------------------------------- #
# Triggers — git-backed YAML is the source of truth; this is a lookup cache   #
# --------------------------------------------------------------------------- #


class Trigger(Base):
    __tablename__ = "triggers"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    owner_user_id: Mapped[str] = mapped_column(
        Text, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    scope_path: Mapped[str] = mapped_column(Text, nullable=False)
    kind: Mapped[str] = mapped_column(Text, nullable=False)        # "delta" | "schedule"
    nl_description: Mapped[str] = mapped_column(Text, nullable=False)
    action_json: Mapped[str] = mapped_column(Text, nullable=False)
    schedule_cron: Mapped[str | None] = mapped_column(Text)
    # IANA timezone name (e.g. "America/Los_Angeles") that ``schedule_cron``
    # is interpreted in. Required when ``kind="schedule"``.
    schedule_timezone: Mapped[str | None] = mapped_column(Text)
    # Optional UTC ISO 8601 anchor — schedule eval skips ticks before this
    # moment, so users can schedule a trigger to start on a specific date.
    schedule_start_at: Mapped[str | None] = mapped_column(Text)
    # UTC ISO 8601 of the most recent fire (or attempted fire). Updated by
    # the schedule evaluator on each tick so croniter advances. DB-only —
    # not persisted to the YAML file (would commit on every fire).
    schedule_last_fired_at: Mapped[str | None] = mapped_column(Text)
    enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("TRUE"))
    file_path: Mapped[str | None] = mapped_column(Text)
    last_edited_at: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[str] = mapped_column(Text, nullable=False, server_default=_NOW_TEXT_DEFAULT)


class TriggerDestination(Base):
    """Catalog of where a trigger fire can be delivered.

    The ``id`` is a stable slug (e.g. ``"event_log"``) referenced from each
    trigger's ``action_json.destination``. ``name`` and ``description`` are
    surfaced to the user — including via the ``get_trigger_destinations``
    agent tool. Seeded by migration ``0004``; new destinations are added by
    follow-up migrations as outbound dispatchers come online.
    """

    __tablename__ = "trigger_destinations"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("''"))
    created_at: Mapped[str] = mapped_column(
        Text, nullable=False, server_default=_NOW_TEXT_DEFAULT
    )


# --------------------------------------------------------------------------- #
# Chat sessions — persisted conversations with the in-app ChatUI              #
# --------------------------------------------------------------------------- #


class ChatSession(Base):
    __tablename__ = "chat_sessions"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    user_id: Mapped[str] = mapped_column(
        Text, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    # NULL until the title-generation task fills it in after the first turn.
    title: Mapped[str | None] = mapped_column(Text)
    # Sessions created to bootstrap "drafting from template" conversations
    # are hidden from the session history list (the row stays so the
    # transcript can be re-rendered if anything in code still has the id).
    hidden: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("FALSE")
    )
    created_at: Mapped[str] = mapped_column(
        Text, nullable=False, server_default=_NOW_TEXT_DEFAULT
    )
    updated_at: Mapped[str] = mapped_column(
        Text, nullable=False, server_default=_NOW_TEXT_DEFAULT
    )

    __table_args__ = (Index("idx_chat_sessions_user_updated", "user_id", "updated_at"),)


class ChatMessage(Base):
    """One turn in a chat session.

    For ``role='user'`` the body is just ``content`` (the raw user text);
    ``events_json`` is NULL. For ``role='assistant'`` ``content`` is the
    final rendered text shown in the bubble, and ``events_json`` is the
    full list of stream events for the turn (text deltas, tool calls,
    tool results, iteration markers) serialized as JSON, so the session
    can be re-rendered with the original tool-call detail.
    """

    __tablename__ = "chat_messages"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    session_id: Mapped[str] = mapped_column(
        Text, ForeignKey("chat_sessions.id", ondelete="CASCADE"), nullable=False
    )
    ordering: Mapped[int] = mapped_column(Integer, nullable=False)
    role: Mapped[str] = mapped_column(Text, nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("''"))
    events_json: Mapped[str | None] = mapped_column(Text)
    # Hidden seed messages live in the LLM history (so the model has the
    # template context) but are filtered out of the rendered transcript.
    hidden: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("FALSE")
    )
    created_at: Mapped[str] = mapped_column(
        Text, nullable=False, server_default=_NOW_TEXT_DEFAULT
    )

    __table_args__ = (
        CheckConstraint(
            "role IN ('user', 'assistant')", name="chat_messages_role_check"
        ),
        Index("idx_chat_messages_session_order", "session_id", "ordering"),
    )


# --------------------------------------------------------------------------- #
# Document templates — admin-managed seed content for new wiki pages          #
# --------------------------------------------------------------------------- #


class DocumentTemplate(Base):
    """Admin-defined template used to seed a brand-new wiki page.

    Selected from the new-doc picker; the template's body is committed
    as the initial content, and ``system_prompt`` (when set) overrides
    the chat agent's system prompt while the user is still drafting.
    """

    __tablename__ = "document_templates"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    name: Mapped[str] = mapped_column(Text, unique=True, nullable=False)
    body: Mapped[str] = mapped_column(Text, nullable=False)
    description: Mapped[str | None] = mapped_column(Text)
    system_prompt: Mapped[str | None] = mapped_column(Text)
    # Admin-controlled ordering for the picker. Lower values render
    # first; ties fall back to ``name`` alphabetical. New rows land at
    # the end (max(sort_order) + 1) so admins decide where they live.
    sort_order: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("0")
    )
    created_by_user_id: Mapped[str | None] = mapped_column(
        Text, ForeignKey("users.id", ondelete="SET NULL")
    )
    created_at: Mapped[str] = mapped_column(
        Text, nullable=False, server_default=_NOW_TEXT_DEFAULT
    )
    updated_at: Mapped[str] = mapped_column(
        Text, nullable=False, server_default=_NOW_TEXT_DEFAULT
    )


class DocumentDraft(Base):
    """Active "drafting from template" state for a wiki page.

    Inserted when a user creates a page from a template; deleted when
    the page body diverges from ``template_body_snapshot`` (i.e. the
    user has made real edits) or when the page is deleted.
    """

    __tablename__ = "document_drafts"

    path: Mapped[str] = mapped_column(Text, primary_key=True)
    template_id: Mapped[str] = mapped_column(
        Text, ForeignKey("document_templates.id", ondelete="CASCADE"), nullable=False
    )
    template_body_snapshot: Mapped[str] = mapped_column(Text, nullable=False)
    created_by_user_id: Mapped[str | None] = mapped_column(
        Text, ForeignKey("users.id", ondelete="SET NULL")
    )
    created_at: Mapped[str] = mapped_column(
        Text, nullable=False, server_default=_NOW_TEXT_DEFAULT
    )


# --------------------------------------------------------------------------- #
# Audit log                                                                   #
# --------------------------------------------------------------------------- #


class Event(Base):
    __tablename__ = "events"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    ts: Mapped[str] = mapped_column(Text, nullable=False, server_default=_NOW_TEXT_DEFAULT)
    kind: Mapped[str] = mapped_column(Text, nullable=False)
    actor: Mapped[str | None] = mapped_column(Text)
    target: Mapped[str | None] = mapped_column(Text)
    payload_json: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'{}'"))

    __table_args__ = (
        Index("idx_events_ts", "ts"),
        Index("idx_events_kind_ts", "kind", "ts"),
    )


# --------------------------------------------------------------------------- #
# Single-row settings tables — id=1 always                                    #
# --------------------------------------------------------------------------- #


class LLMSettings(Base):
    __tablename__ = "llm_settings"

    # ``id`` is always 1 — the CHECK below + the singleton constraint enforce
    # that. Mark autoincrement=False so SQLAlchemy doesn't synthesize a
    # SERIAL sequence we'd never read from.
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=False)
    provider: Mapped[str] = mapped_column(Text, nullable=False)
    model: Mapped[str] = mapped_column(Text, nullable=False)
    anthropic_api_key: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("''"))
    openai_api_key: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("''"))
    gemini_api_key: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("''"))
    ollama_base_url: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("''"))
    provider_models: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, server_default=text("'{}'::jsonb"))
    updated_at: Mapped[str] = mapped_column(Text, nullable=False, server_default=_NOW_TEXT_DEFAULT)

    __table_args__ = (CheckConstraint("id = 1", name="llm_settings_singleton"),)


class WebSettings(Base):
    __tablename__ = "web_settings"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=False)
    serper_api_key: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("''"))
    firecrawl_api_key: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("''"))
    updated_at: Mapped[str] = mapped_column(Text, nullable=False, server_default=_NOW_TEXT_DEFAULT)

    __table_args__ = (CheckConstraint("id = 1", name="web_settings_singleton"),)


class IngestSettings(Base):
    __tablename__ = "ingest_settings"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=False)
    max_doc_chars: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("100000")
    )
    api_key: Mapped[str | None] = mapped_column(Text, nullable=True)
    updated_at: Mapped[str] = mapped_column(Text, nullable=False, server_default=_NOW_TEXT_DEFAULT)

    __table_args__ = (CheckConstraint("id = 1", name="ingest_settings_singleton"),)


class BraintrustSettings(Base):
    __tablename__ = "braintrust_settings"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=False)
    project: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("''"))
    api_key: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("''"))
    enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default=text("false"))
    updated_at: Mapped[str] = mapped_column(Text, nullable=False, server_default=_NOW_TEXT_DEFAULT)

    __table_args__ = (CheckConstraint("id = 1", name="braintrust_settings_singleton"),)


# --------------------------------------------------------------------------- #
# Agent activity registry                                                     #
# --------------------------------------------------------------------------- #


class AgentActivity(Base):
    __tablename__ = "agent_activity"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    user_id: Mapped[str] = mapped_column(
        Text, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    # Null when the agent didn't name itself.
    agent_name: Mapped[str | None] = mapped_column(Text)
    doc_path: Mapped[str] = mapped_column(Text, nullable=False)
    activity: Mapped[str] = mapped_column(Text, nullable=False)
    description: Mapped[str | None] = mapped_column(Text)   # null = "N/A" in rendered frontmatter
    registered_at: Mapped[str] = mapped_column(
        Text, nullable=False, server_default=_NOW_TEXT_DEFAULT
    )
    expires_at: Mapped[str] = mapped_column(Text, nullable=False)   # ISO 8601 UTC
    # Queue msg_id of the cleanup task scheduled to fire at expires_at.
    # Tracked so re-registration (which slides expires_at forward) can
    # cancel the prior scheduled fire instead of leaking it as an orphan
    # delayed message. Null when no cleanup has been scheduled yet or
    # when the prior message has already fired.
    cleanup_msg_id: Mapped[int | None] = mapped_column(BigInteger)

    __table_args__ = (
        CheckConstraint(
            "activity IN ('read', 'wrote')", name="agent_activity_kind_check"
        ),
        # One row per (user, agent): a new upsert replaces the prior row
        # in place. Postgres 15+ NULLS NOT DISTINCT lets nullable
        # agent_name participate in uniqueness directly — no
        # COALESCE-to-empty-string workaround.
        UniqueConstraint(
            "user_id", "agent_name",
            name="idx_agent_activity_user_agent",
            postgresql_nulls_not_distinct=True,
        ),
        Index("idx_agent_activity_doc_path", "doc_path"),
        Index("idx_agent_activity_expires_at", "expires_at"),
    )


# --------------------------------------------------------------------------- #
# Cron state — per-(queue, task) last-fired timestamp so the periodic         #
# scheduler can survive restarts without silently dropping or stampeding      #
# missed fires. See app/tasks/queue.py:_run_periodic_scheduler.               #
# --------------------------------------------------------------------------- #


class CronState(Base):
    __tablename__ = "cron_state"

    queue_name: Mapped[str] = mapped_column(Text, primary_key=True)
    task_name: Mapped[str] = mapped_column(Text, primary_key=True)
    last_fired_at: Mapped[str | None] = mapped_column(Text)


class WikiSeedState(Base):
    """One-shot marker: has the bundled onboarding seed run on this DB?

    Stamped to an ISO-8601 timestamp the first time the lifespan's
    ``seed_if_empty`` either writes the seed or observes that the wiki
    already has user content. Once non-null, the seed will never run
    again on this database — so if a user deletes every onboarding
    page and reboots, they get an empty wiki, not a re-seed.

    Tied to the database (not the wiki working tree) on purpose: the
    wiki can be wiped (volume reset, manual ``rm -rf``) and the marker
    survives, preserving the user's intent to start fresh.
    """

    __tablename__ = "wiki_seed_state"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=False)
    seeded_at: Mapped[str | None] = mapped_column(Text, nullable=True)

    __table_args__ = (CheckConstraint("id = 1", name="wiki_seed_state_singleton"),)



# --------------------------------------------------------------------------- #
# Permissions — groups, ACLs, page ownership                                  #
# --------------------------------------------------------------------------- #
#
# Wiki page permission state lives entirely in Postgres. The git repo and
# the wiki-data volume do not carry it; clones / volume copies / filesystem
# backups lose all of these tables. See local_data/wiki/permissions/.


class Group(Base):
    __tablename__ = "groups"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    name: Mapped[str] = mapped_column(Text, unique=True, nullable=False)
    description: Mapped[str | None] = mapped_column(Text)
    created_by_user_id: Mapped[str | None] = mapped_column(
        Text, ForeignKey("users.id", ondelete="SET NULL")
    )
    created_at: Mapped[str] = mapped_column(
        Text, nullable=False, server_default=_NOW_TEXT_DEFAULT
    )


class GroupMember(Base):
    __tablename__ = "group_members"

    group_id: Mapped[str] = mapped_column(
        Text, ForeignKey("groups.id", ondelete="CASCADE"), primary_key=True
    )
    user_id: Mapped[str] = mapped_column(
        Text, ForeignKey("users.id", ondelete="CASCADE"), primary_key=True
    )
    added_at: Mapped[str] = mapped_column(
        Text, nullable=False, server_default=_NOW_TEXT_DEFAULT
    )


class WikiOwner(Base):
    """Per-page ownership.

    Keyed by canonicalized path (``app.wiki.filesystem.safe_rel_path`` —
    no leading slash). The owner has unconditional read/write/share/
    transfer/delete on the page; ACL entries grant *additional* access.
    ``owner_user_id`` is nullable so account deletion can ``SET NULL``
    without dropping the page row — admin re-assigns via the transfer
    endpoint. A page may exist on disk without a row here (e.g. seeded
    content committed via raw git outside the lifecycle hook) — the
    resolver treats "no owner row" as "no owner shortcut" and falls
    back to ACLs.
    """

    __tablename__ = "wiki_owners"

    path: Mapped[str] = mapped_column(Text, primary_key=True)
    owner_user_id: Mapped[str | None] = mapped_column(
        Text, ForeignKey("users.id", ondelete="SET NULL")
    )


class AclEntry(Base):
    """One grant of ``read`` or ``write`` on a wiki page or folder.

    ``resource_path`` is canonical (no leading or trailing slash); ``""``
    is the wiki root (folder grants only). For ``principal_kind='everyone'``
    the row matches every authenticated user and ``principal_id`` is NULL;
    for ``user``/``group`` the id references ``users.id`` or ``groups.id``
    but is *not* a real foreign key (one column can't FK to two tables).
    Existence is enforced at the repo layer.

    Grants are additive only — no explicit deny. ``write`` does not
    auto-imply ``read`` in storage; the resolver unions matching rows
    and treats ``write`` as also granting ``read``.
    """

    __tablename__ = "acl_entries"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    resource_kind: Mapped[str] = mapped_column(Text, nullable=False)
    resource_path: Mapped[str] = mapped_column(Text, nullable=False)
    principal_kind: Mapped[str] = mapped_column(Text, nullable=False)
    principal_id: Mapped[str | None] = mapped_column(Text)
    permission: Mapped[str] = mapped_column(Text, nullable=False)
    granted_by_user_id: Mapped[str | None] = mapped_column(
        Text, ForeignKey("users.id", ondelete="SET NULL")
    )
    created_at: Mapped[str] = mapped_column(
        Text, nullable=False, server_default=_NOW_TEXT_DEFAULT
    )

    __table_args__ = (
        CheckConstraint(
            "resource_kind IN ('page', 'folder')",
            name="acl_entries_kind_check",
        ),
        CheckConstraint(
            "principal_kind IN ('user', 'group', 'everyone')",
            name="acl_entries_principal_kind_check",
        ),
        CheckConstraint(
            "permission IN ('read', 'write')",
            name="acl_entries_permission_check",
        ),
        CheckConstraint(
            "(principal_kind = 'everyone') = (principal_id IS NULL)",
            name="acl_entries_principal_id_alignment",
        ),
        UniqueConstraint(
            "resource_kind",
            "resource_path",
            "principal_kind",
            "principal_id",
            "permission",
            name="acl_entries_unique_grant",
            postgresql_nulls_not_distinct=True,
        ),
        Index("idx_acl_resource", "resource_kind", "resource_path"),
        Index("idx_acl_principal", "principal_kind", "principal_id"),
    )
