"""onyx-editor coedit ydoc snapshot and updates

Revision ID: 532749e66b8f
Revises: 5c4a9e1b7d38
Create Date: 2026-07-22 05:06:08.636761+00:00
"""
from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '532749e66b8f'
down_revision: str | None = '5c4a9e1b7d38'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coedit_updates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('author_user_id', sa.Text(), nullable=True),
    sa.Column('update_bytes', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')"), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['coedit_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'seq', name='idx_coedit_updates_session_seq')
    )
    op.add_column('coedit_sessions', sa.Column('ydoc_snapshot', sa.LargeBinary(), nullable=True))
    op.add_column('coedit_sessions', sa.Column('ydoc_seq', sa.BigInteger(), server_default=sa.text('0'), nullable=False))
    op.add_column('coedit_sessions', sa.Column('ydoc_checkpointed_seq', sa.BigInteger(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coedit_sessions', 'ydoc_checkpointed_seq')
    op.drop_column('coedit_sessions', 'ydoc_seq')
    op.drop_column('coedit_sessions', 'ydoc_snapshot')
    op.drop_table('coedit_updates')
    # ### end Alembic commands ###
