"""agent wiki editor coedit yjs schema

``create_all`` in 0001 already materializes ``coedit_updates`` and the
current ``coedit_sessions`` shape on fresh installs — guarded the same way
as 0009_user_settings.py so upgrading an existing (OT-shaped) DB and
building a fresh one both work.

Revision ID: cf4e6e443836
Revises: d5e8a1c4f7b2
Create Date: 2026-07-24 02:44:04.718742+00:00
"""
from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'cf4e6e443836'
down_revision: str | None = 'd5e8a1c4f7b2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if not inspector.has_table('coedit_updates'):
        op.create_table('coedit_updates',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('session_id', sa.BigInteger(), nullable=False),
        sa.Column('seq', sa.BigInteger(), nullable=False),
        sa.Column('author_user_id', sa.Text(), nullable=True),
        sa.Column('update_bytes', sa.LargeBinary(), nullable=False),
        sa.Column('created_at', sa.Text(), server_default=sa.text("to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')"), nullable=False),
        sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['session_id'], ['coedit_sessions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('session_id', 'seq', name='idx_coedit_updates_session_seq')
        )

    if inspector.has_table('coedit_ops'):
        op.drop_table('coedit_ops')

    columns = {c['name'] for c in inspector.get_columns('coedit_sessions')}
    if 'ydoc_snapshot' not in columns:
        op.add_column('coedit_sessions', sa.Column('ydoc_snapshot', sa.LargeBinary(), nullable=True))
    if 'ydoc_seq' not in columns:
        op.add_column('coedit_sessions', sa.Column('ydoc_seq', sa.BigInteger(), server_default=sa.text('0'), nullable=False))
    if 'ydoc_checkpointed_seq' not in columns:
        op.add_column('coedit_sessions', sa.Column('ydoc_checkpointed_seq', sa.BigInteger(), server_default=sa.text('0'), nullable=False))
    if 'buffer_text' in columns:
        op.drop_column('coedit_sessions', 'buffer_text')
    if 'version' in columns:
        op.drop_column('coedit_sessions', 'version')
    if 'checkpointed_version' in columns:
        op.drop_column('coedit_sessions', 'checkpointed_version')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coedit_sessions', sa.Column('checkpointed_version', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('coedit_sessions', sa.Column('version', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('coedit_sessions', sa.Column('buffer_text', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False))
    op.drop_column('coedit_sessions', 'ydoc_checkpointed_seq')
    op.drop_column('coedit_sessions', 'ydoc_seq')
    op.drop_column('coedit_sessions', 'ydoc_snapshot')
    op.create_table('coedit_ops',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('seq', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('author_user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('base_version', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('op_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("to_char((now() AT TIME ZONE 'UTC'::text), 'YYYY-MM-DD HH24:MI:SS'::text)"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], name=op.f('coedit_ops_author_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['coedit_sessions.id'], name=op.f('coedit_ops_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('coedit_ops_pkey')),
    sa.UniqueConstraint('session_id', 'seq', name=op.f('idx_coedit_ops_session_seq'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('coedit_updates')
    # ### end Alembic commands ###
